### ISSUE TITLE
HTTP Caching

### ISSUE THREAD

**Issue by johanjanssens** [joomlatools/joomlatools-framework#36]
Create a dispatcher http transport that transparently caches the response based on the request state and handles cache validation.

See: https://github.com/joomlatools/textman/issues/112
See: https://github.com/joomlatools/joomlatools-pages/issues/21

### Resources

- https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/http-caching
- https://www.mnot.net/blog/2017/03/16/browser-caching
- https://tools.ietf.org/html/rfc7234

Other 

- https://stackoverflow.com/questions/1046966/whats-the-difference-between-cache-control-max-age-0-and-no-cache
- https://www.keycdn.com/blog/http-cache-headers/
- https://support.cloudflare.com/hc/en-us/articles/218505467-Does-Cloudflare-support-ETag-headers-

### Notes

1. Headers in the 304 update the stored response headers
2. Clicking refresh: Cache-Control: max-age=0
3. Disabling cache: Cache-Control: no-cache

### Todo

- [ ] HTTP specifies that caches should be invalidated when unsafe request methods are used and the response is successful – i.e., a 2xx or 3xx status code. Unsafe methods include POST, PUT and DELETE, as well as unknown status codes.

- [ ] HTTP lets servers specify that the cache key depends on more than just the URL by using the Vary header, which lists the request headers whose values should be added to it. This secondary cache key enables things like caching compressed content, and generally in supporting content negotiation.

- [x] Add Support for s-maxage to allow to define a separate proxy cache time and browser cache time. See: https://support.cloudflare.com/hc/en-us/articles/202775670-How-Do-I-Tell-Cloudflare-What-to-Cache- (see https://github.com/joomlatools/joomlatools-framework/pull/266)
